name: CI meta-sifive

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        target: [freedom-u540, qemuriscv64, unmatched]
    name: Build images for ${{ matrix.target }}
    runs-on: self-hosted
    steps:
      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool
      #     sudo apt-get clean
      #     pip install --user kas
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          path: meta-sifive
      - name: Build images
        run: kas build --update ./meta-sifive/scripts/kas/${{ matrix.target }}.yml
      - name: Upload images
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_number }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/build/tmp-glibc/deploy/images/${{ matrix.target }}/
